// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8o6FT96LR3n5H4otnjT_VOolrIWpoljk',
    appId: '1:655487028536:web:8d4041361f40c9b71105cd',
    messagingSenderId: '655487028536',
    projectId: 'safe-space-c7868',
    authDomain: 'safe-space-c7868.firebaseapp.com',
    storageBucket: 'safe-space-c7868.appspot.com',
    measurementId: 'G-PDLLLLK3C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv3hrPz4Y5C1G6GSRV2p9E8OK4tWYTNzc',
    appId: '1:655487028536:android:fe742e0505bdf71c1105cd',
    messagingSenderId: '655487028536',
    projectId: 'safe-space-c7868',
    storageBucket: 'safe-space-c7868.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5f70VgtnCvHgUCspXE0dvozrWTBSYzJ0',
    appId: '1:655487028536:ios:d39efbbbeedd1f7e1105cd',
    messagingSenderId: '655487028536',
    projectId: 'safe-space-c7868',
    storageBucket: 'safe-space-c7868.appspot.com',
    iosClientId: '655487028536-j3a0iet8cl29qv5sa776ur919g5253ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeSpace',
  );
}
